# move cards
name: 'Glo Add Comment To Cards'
description: 'GitHub Action to add a comment to cards'
branding:
  color: 'blue'
  icon: 'tag'
inputs:
  authToken:
    description: Auth token for user
    required: true
  cards:
    description: Array of { cardId, boardId } objects
    required: true
  comment:
    description: Comment to add to the card
    required: true
runs:
  using: 'node12'
  main: 'lib/index.js'
