# move cards
name: 'Glo Add Assignee To Cards'
description: 'GitHub Action to add an assignee to cards'
branding:
  color: 'blue'
  icon: 'tag'
inputs:
  authToken:
    description: Auth token for user
    required: true
  cards:
    description: Array of { cardId, boardId } objects
    required: true
  assignee:
    description: Username of user to assign to card
    required: true
runs:
  using: 'node12'
  main: 'lib/index.js'
