# move cards
name: 'Glo Move Cards To Column'
description: 'GitHub Action to move cards to a column'
branding:
  color: 'blue'
  icon: 'tag'
inputs:
  authToken:
    description: Auth token for user
    required: true
  cards:
    description: Array of { cardId, boardId } objects
    required: true
  column:
    description: Name of column to move cards to
    required: true
runs:
  using: 'node12'
  main: 'lib/index.js'
