# move cards
name: 'Glo Parse Links'
description: 'GitHub Action to parse links for cards'
branding:
  color: 'blue'
  icon: 'tag'
inputs:
  authToken:
    description: Auth token for user
    required: true
outputs:
  boards:
    description: Stringified array of boards with list of cards
runs:
  using: 'node12'
  main: 'lib/index.js'
